### PR TITLE
"Mined" to "Minted" for StakeMint transactions & Readme update

### PR DESCRIPTION
**Pull request by beatles1**
I am a noob so this could be completely wrong and not work. As noted in this reddit thread it makes more sense to say "Minted": http://www.reddit.com/r/MintCoin/comments/22818m/mint_wallet_mining_by_itself_wtf_is_going_on/

Also Readme update with fixed markup and PoW removal info.

### CODE REVIEW

**Comment by unek** [comment]
Language string [like this one](https://github.com/mintcoinproject/mintcoin/blob/master/src/qt/locale/bitcoin_en.ts#L1906-L1910) would be nice, too.

**Comment by beatles1** [comment]
Waiting for confirmation of Russian translation: http://redd.it/229zbf

**Comment by unek** [comment]
I wouldn't care about that, since the Russian translation isn't complete anyway (it doesn't have any PoS-related strings included)

**Comment by beatles1** [comment]
Alright, will leave it there then. I cannot test as my coins are not old enough yet so I have done what I can here. Sorry for the readme fix being in the same pull, very new to GitHub.

**Pull request merged**
