### PR TITLE
Add extra step for Ubuntu install

### PR DESCRIPTION
**Pull request by pjf**
Ubuntu 13.10 doesn't have `libdb4.8++-dev` packages by default, but they're in the bitcoin ppa. This patch adds the relevant install instructions.

Note: This could probably be even better with a fancy `ppa:` line, but as I'm currently in transit I don't quite have the chance to figure that out.

### CODE REVIEW

**Comment by pjf** [comment]
Update: This now uses a proper ppa line.

**Comment by unek** [comment]
I see a typo ;)

> up to doate

**Comment by pjf** [comment]
Dang it... one moment. :)

**Comment by pjf** [comment]
Fixed!

**Pull request merged**
