### PR TITLE
Stake notify icon

### PR DESCRIPTION
**Pull request by swordfish6975**
Not sure if this will work not setup on windows to debug wallets just yet...

### CODE REVIEW

**Comment by unek** [comment]
Doesn't seem to compile for me.

**Comment by swordfish6975** [comment]
yep can confirm - needs lots more work :(

**Comment by mintcoinproject** [comment]
this is only the UI part, the core change will be a lot since the mintcoin base code is not the latest pow/pos codebase.

**Comment by Propstomasses** [comment]
Well, nTargetspacing from original blackcoin source does not work here, since Mintcoin target spacing is split in to two. nTargetSpacing and nStakeTargetSpacing.
Surely someone can have a look and figure out how to properly do it.

**Pull request closed without merging**
